### ISSUE TITLE
Content Security Policy Violations

### ISSUE THREAD

**Issue by ehubbell** [lukes/ember-cli-zopim-live-chat#1]
Hi - I've included your library in our project and everything seems to work great however I'm seeing a bunch of content security policy violations show up due to the inclusion of zopim. Do you know how to fix this? I've tried adding `*.zopim.com` to the necessary lines in our 'config/environment' file but that didn't work. Please advise.

Thanks,
Eric

**Comment by lukes** [comment]
Hi, 

I created an Ember app with a fresh version of ember-cli today (v 1.13.12), and found this config worked for me:

``` javascript
ENV.contentSecurityPolicy = {
  'script-src': "'self' 'unsafe-inline' 'unsafe-eval' *.zopim.com"
}
```

Does that work for you?
